### ISSUE TITLE
go-ipld-cbor dependency unavailable

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-car#5]
The go-ipld-cbor package referenced here (1.4.9 QmeyKxwBJgB7AP1DgoMAbqHajMnt4C6TuubsKBRVGZVFuH) isn't available.

Additionally the latest version in https://github.com/ipfs/go-ipld-cbor is 1.3.0.

**Comment by dignifiedquire** [comment]
the version is available here https://github.com/filecoin-project/go-ipld-cbor (well at least 1.4.8)

**Comment by lgierth** [comment]
Ugh, any reason for the fork? ` This branch is 42 commits ahead, 33 commits behind ipfs:master`

**Comment by dignifiedquire** [comment]
Yes, we have been using the version using refmt for 6month or so, and needed to be able to publish versions.

**Comment by lgierth** [comment]
Okay, could someone at least publish that gx package somewhere then? :) `QmeyKxwBJgB7AP1DgoMAbqHajMnt4C6TuubsKBRVGZVFuH`

**Comment by dignifiedquire** [comment]
I believe that version was published by @whyrusleeping

**Comment by frrist** [comment]
Going to close this out as the project is generally consumed via go.mod. Feel free to reopen if you have a case for gx support here
